apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: metabase-resizable
  namespace: {{ .Release.Namespace }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
  replication-type: none
reclaimPolicy: Retain
#volumeBindingMode: Immediate
allowVolumeExpansion: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metabase-data
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: "metabase-resizable"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.disksize }}Gi
